repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        additional_dependencies: ["ruff==0.4.4"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--check-untyped-defs"]

  - repo: local                # ← new list item, indented two spaces
    hooks:                     # ← aligned under “repo:”
      - id: pytest             # ← each hook indented two more spaces
        name: pytest
        entry: pytest
        language: system
        types: [python]
