name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest       # identical container every run
    steps:
      - uses: actions/checkout@v4  # step 1: pull your code
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}  # step 2: same Python as you use locally
      - run: pip install ruff mypy black pytest
      - run: ruff .
      - run: mypy --check-untyped-defs .
      - run: pytest
